
def add_local_machine_ssh_pub_key(config)
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      echo "#{ssh_pub_key}" >> /home/vagrant/.ssh/authorized_keys
      echo "#{ssh_pub_key}" >> /root/.ssh/authorized_keys
    SHELL
  end
end


def define_machine(config, num)
  # vm_box = "ubuntu/focal64"             # If you could downlowd box using VPN
  vm_box = "Boxes/focal-server-cloudimg-amd64-vagrant.box"

  config.vm.define "vm_#{num}" do |manager|
    manager.vm.box = vm_box
    manager.vm.network :private_network, ip: "10.100.199.20#{num}"

    manager.vm.provider "virtualbox" do |vb|
      vb.name = "vm_#{num}"
      vb.memory = "1000"
    end

    add_local_machine_ssh_pub_key(manager)
  end
end

Vagrant.configure("2") do |config|
    define_machine(config, 1)
    define_machine(config, 2)
end