- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Check if Apache service is running
  service_facts:

- name: Debug message for Apache service status
  debug:
    msg: "Apache service is running"
  when: "'apache2' in ansible_facts.services and ansible_facts.services['apache2']['state'] == 'running'"