- name: Install PostgreSQL and psycopg2
  become: yes
  apt:
    name: 
      - postgresql-12
      - postgresql-client-12
      - python3-psycopg2
    state: latest

- name: Ensure PostgreSQL service is started and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Set password for postgres user
  become: yes
  become_user: postgres
  postgresql_user:
    db: postgres
    name: postgres
    password: postgres
    priv: ALL
    expires: infinity

- name: Drop existing database if exists
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: hotels_db
    state: absent

- name: Create new database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: hotels_db
    state: present

- name: Initialize database with data from SQL file
  become: yes
  become_user: postgres
  postgresql_query:
    db: hotels_db
    path_to_script: "{{ role_path }}/files/data.sql"

- name: Check if PostgreSQL service is running
  service_facts:

- name: Debug message for PostgreSQL service status
  debug:
    msg: "PostgreSQL service is running"
  when: "'postgresql' in ansible_facts.services and ansible_facts.services['postgresql']['state'] == 'running'"
