- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install Docker and Docker Compose
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - docker-compose

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yml
    dest: /home/vagrant/docker-compose.yml

- name: Deploy microservices application
  command: docker-compose up -d
  args:
    chdir: /home/vagrant 