myhosts:
  hosts:
    consul_server:
      ansible_host: 10.100.199.201
      ansible_user: vagrant

    api:
      ansible_host: 10.100.199.202
      ansible_user: vagrant

    db:
      ansible_host: 10.100.199.203
      ansible_user: vagrant
