Vagrant.configure("2") do |config|
    # vm_box = "ubuntu/focal64"             # If you could downlowd box using VPN
    vm_box = "Boxes/focal-server-cloudimg-amd64-vagrant.box"

    config.vm.define "consul_server" do |machine|
      machine.vm.box = vm_box
      machine.vm.network :private_network, ip: "10.100.199.200"
      machine.vm.network :forwarded_port, guest: 8500, host: 8500
      machine.vm.hostname = "consul-server"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "consul-server"
        vb.memory = "4000"
      end
      # Provisions
      machine.vm.provision "shell", inline: <<-SHELL
        sudo apt update; sudo apt upgrade -y
        sudo apt install -y python3-pip
        pip install ansible
        ln -s /vagrant/ansible ~/ansible
        echo 'Host api' >> /home/vagrant/.ssh/config
        echo '  HostName 10.100.199.201' >> /home/vagrant/.ssh/config
        echo '  User vagrant' >> /home/vagrant/.ssh/config
        echo '  Port 22' >> /home/vagrant/.ssh/config
      SHELL
    end

    config.vm.define "api" do |machine|
      machine.vm.box = vm_box
      machine.vm.network :private_network, ip: "10.100.199.201"
      machine.vm.network :forwarded_port, guest: 8081, host: 8081
      machine.vm.network :forwarded_port, guest: 8082, host: 8082 #??
      machine.vm.network :forwarded_port, guest: 8087, host: 8087
      machine.vm.hostname = "api"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "api"
        vb.memory = "8000" # more memory for Part 1 from 4000
      end
      # Provisions
    end
  
    config.vm.define "db" do |machine|
      machine.vm.box = vm_box
      machine.vm.network :private_network, ip: "10.100.199.202"
      machine.vm.network :forwarded_port, guest: 8080, host: 8082
      machine.vm.hostname = "db"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "db"
        vb.memory = "4000"
      end
      # Provisions
    end
end