def provision_run(machine, commands = [])
  machine.vm.provision "shell", inline: <<-SHELL
    #{commands.join("\n")}
  SHELL
end


# fix required
def provision_ssh_keygen(machine)
  machine.vm.provision "shell", inline: <<-SHELL
    ssh-keygen -q -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
  SHELL
end

Vagrant.configure("2") do |config|
    # vm_box = "ubuntu/focal64"             # If you could downlowd box using VPN
    vm_box = "Boxes/focal-server-cloudimg-amd64-vagrant.box"
  
    config.vm.define "node01" do |machine|
      machine.vm.box = vm_box
      machine.vm.network :private_network, ip: "10.100.199.201"
      machine.vm.network :forwarded_port, guest: 8081, host: 8081
      machine.vm.network :forwarded_port, guest: 8087, host: 8087
      machine.vm.hostname = "node01"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "node01"
        vb.memory = "8000" # more memory for Part 1 from 4000
      end
      # Provisions
    end
  
    config.vm.define "node02" do |machine|
      machine.vm.box = vm_box
      machine.vm.network :private_network, ip: "10.100.199.202"
      machine.vm.network :forwarded_port, guest: 8080, host: 8082
      machine.vm.hostname = "node02"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "node02"
        vb.memory = "4000"
      end
      # Provisions
    end

    config.vm.define "manager" do |machine|
      machine.vm.box = vm_box
      machine.vm.network :private_network, ip: "10.100.199.200"
      machine.vm.network :forwarded_port, guest: 8080, host: 8080
      machine.vm.hostname = "manager"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "manager"
        vb.memory = "4000"
      end
      # Provisions
      machine.vm.provision "shell", inline: <<-SHELL
        sudo apt update; sudo apt upgrade -y
        sudo apt install -y python3-pip
        pip install ansible
        ln -s /vagrant/ansible ~/ansible
        echo 'Host node01' >> /home/vagrant/.ssh/config
        echo '  HostName 10.100.199.201' >> /home/vagrant/.ssh/config
        echo '  User vagrant' >> /home/vagrant/.ssh/config
        echo '  Port 22' >> /home/vagrant/.ssh/config
      SHELL
    end
end