- name: Install consul
  apt:
    name: consul
    state: present

- name: Replace old consul with consul-v1.18.1
  copy:
    src: consul-v1.18.1
    dest: /usr/bin/consul

- name: Remove all contents from /etc/consul.d/
  ansible.builtin.file:
    path: /etc/consul.d/
    state: absent

- name: Recreate /etc/consul.d/ directory
  ansible.builtin.file:
    path: /etc/consul.d/
    state: directory

- name: Copy consul_server.hcl to /etc/consul.d/
  copy:
    src: consul_server.hcl
    dest: /etc/consul.d/config.hcl

- name: Reload systemd daemon to recognize changes
  systemd:
    daemon_reload: yes

- name: Enable and start consul service
  systemd:
    name: consul
    enabled: yes
    state: started

- name: Check consul service status
  command: systemctl status consul
  register: consul_status
  changed_when: false

- debug:
    var: consul_status.stdout_lines
