- name: Deploy Consul Server
  hosts: consul_server
  become: yes
  roles:
    - common
    - install_consul_server

- name: Setup Database
  hosts: db
  become: yes
  vars:
    consul_service_name: "postgres-service"
  roles:
    - common
    - install_consul_client
    - install_db

- name: Setup API
  hosts: api
  become: yes
  vars:
    consul_service_name: "hotel-service"
  roles:
    - common
    - install_consul_client
    - install_hotels_service

